version: "3.9"

services:
  backend:
    build:
      context: ../../apps/backend-api
      dockerfile: Dockerfile
    env_file:
      - ../../env/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/backend-api:/app
    command: "npm run dev"

  react:
    build:
      context: ../../apps/frontend-react
    env_file:
      - ../../env/.env.development
    ports:
      - "5173:5173"
    volumes:
      - ../../apps/frontend-react:/app
    command: "npm run dev -- --host 0.0.0.0"

  vue:
    build:
      context: ../../apps/frontend-vue
    env_file:
      - ../../env/.env.development
    ports:
      - "5174:5173"
    volumes:
      - ../../apps/frontend-vue:/app
    command: "npm run dev -- --host 0.0.0.0"

