name: Generate API Docs

on:
  push:
    paths:
      - "apps/backend-api/openapi.yaml"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate HTML docs
        run: |
          npm install -g redoc-cli
          redoc-cli bundle apps/backend-api/openapi.yaml -o public/api-docs.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: public/api-docs.html

